WITH COMPENSATION AS (
    SELECT NO_CARTE,
        LEFT(NO_CARTE, 6) AS BIN6,
        NO_AUTORISATION,
        CD_BANQUE_ACQUEREUR,
        LB_ETABLISSEMENT_ACQUEREUR AS LB_BANQUE_ACQUEREUR,
        CD_BANQUE_EMETTEUR,
        LB_ETABLISSEMENT_EMETTEUR AS LB_BANQUE_EMETTEUR,
        LB_ENSEIGNE_COMMERCIAL AS LB_COMMERCANT,
        CD_PAYS_COMMERCANT,
        CD_DEV_TRANSACTION AS CD_DEVISE,
        CD_ERT AS ERT_COMPENS,
        CD_MCC,
        LB_MCC,
        CD_MODE_LECTURE_CARTE,
        INITCAP(LB_MODE_LECTURE_CARTE) AS LB_MODE_LECTURE_CARTE,
        CD_NATURE_OPERATION,
        INITCAP(LB_NATURE_OPERATION_MONETIQUE) AS LB_NATURE_OPERATION_MONETIQUE,
        CD_ORIGINE_FLUX,
        CASE
            WHEN CD_ORIGINE_FLUX = "A" THEN "Intra-groupe (CE, BP et sous participants)"
            WHEN CD_ORIGINE_FLUX = "D" THEN "Domestique extra-groupe"
            WHEN CD_ORIGINE_FLUX = "E" THEN "International"
            ELSE null
        END AS LB_ORIGINE_FLUX,
        TOP_VISA_NATIVE,
        CD_SPC AS CD_SCHEME,
        CASE
            WHEN CD_SPC = "V" THEN "VISA"
            WHEN CD_SPC = "M" THEN "MasterCard"
            WHEN CD_SPC = "9" THEN "CB"
            ELSE null
        END AS LB_SCHEME,
        ID_TOKEN_REQUESTOR,
        CASE
            WHEN ID_TOKEN_REQUESTOR = "40010030273" THEN "Apple Pay"
            WHEN ID_TOKEN_REQUESTOR = "40010043095" THEN "Samsung Pay"
            WHEN ID_TOKEN_REQUESTOR = "40010069887" THEN "Garmin Pay"
            WHEN ID_TOKEN_REQUESTOR = "40010081763" THEN "Swatch Pay"
            WHEN ID_TOKEN_REQUESTOR = "40010075001" THEN "Google Pay"
            WHEN ID_TOKEN_REQUESTOR = "40010036958" THEN "PayPal"
            WHEN ID_TOKEN_REQUESTOR = "40010051602" THEN "Amazon"
            WHEN ID_TOKEN_REQUESTOR = "40010077761" THEN "Uber"
            WHEN ID_TOKEN_REQUESTOR = "40010069917" THEN "Stripe"
            WHEN ID_TOKEN_REQUESTOR = "40010033267" THEN "Microsoft"
            WHEN ID_TOKEN_REQUESTOR = "40010062941" THEN "Adyen"
            WHEN ID_TOKEN_REQUESTOR = "40010062878" THEN "PlayStation"
            WHEN ID_TOKEN_REQUESTOR = "40010070315" THEN "AliPay"
            ELSE null
        END AS LB_TOKEN_REQUESTOR,
        ID_TOKEN_REQUESTOR IN (
            "40010030273",
            "40010043095",
            "40010069887",
            "40010081763",
            "40010075001"
        ) AS TOP_XPAY,
        IF(CD_TYPE_DEBIT IN ("D", "I"), CD_TYPE_DEBIT, null) AS CD_TYPE_DEBIT,
        DT_COMPENSATION,
        DATE(DT_TRANSACTION) AS DT_TRANSACTION,
        MT_COMP_TRANSACTION AS Montant,
        CASE
            WHEN MT_COMP_TRANSACTION <= 30 THEN "000 - 030"
            WHEN MT_COMP_TRANSACTION <= 100 THEN "030 - 100"
            WHEN MT_COMP_TRANSACTION <= 250 THEN "100 - 250"
            WHEN MT_COMP_TRANSACTION <= 500 THEN "250 - 500"
            ELSE "500 - +++"
        END AS MT_TRANCHE_RTS,
        NO_CONTRAT_COMMERCANT,
        NO_SIRET,
        CD_PAYS_ACQUEREUR AS CD_PAYS_ACQUEREUR_COMPENS,
        IF(
            (CD_RES_ETRANGER IS NULL)
            OR (CD_PDT_ETRANGER IS NULL),
            NULL,
            CONCAT(CD_RES_ETRANGER, CD_PDT_ETRANGER)
        ) AS CD_PDT_CARTE,
        CD_NATURE_OPERATION = "C" AS TOP_FACTURE_CREDIT
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_Dataset_Porteur.DS_RCOMP_DWH`
    WHERE (
            DT_EXTRACTION BETWEEN DATE("2024-10-01 00:00:00+00:00") AND DATE_ADD(DATE("2025-10-31"), INTERVAL "30" DAY)
        )
        AND CD_ERT != "80"
        AND (
            DATE(DT_TRANSACTION) BETWEEN DATE("2024-10-01 00:00:00+00:00") AND DATE("2025-10-31")
        )
),
REF_ETAB AS (
    SELECT ID_ETABLISSEMENT AS CD_BANQUE_ACQUEREUR,
        ID_ETABLISSEMENT AS CD_BANQUE_EMETTEUR,
        CASE
            WHEN ID_ETABLISSEMENT = "16528" THEN "XPOLLENS"
            WHEN ID_ETABLISSEMENT = "16378" THEN "PAYPLUG"
            WHEN ID_ETABLISSEMENT = "18370" THEN "ORANGE BANK"
            WHEN ID_ETABLISSEMENT = "12869" THEN "ONEY"
            WHEN ID_ETABLISSEMENT = "19733" THEN "OLKY PAYMENT"
            WHEN ID_ETABLISSEMENT = "40978" THEN "PALATINE"
            WHEN ID_ETABLISSEMENT = "30258" THEN "BP AFFILIES"
            WHEN ID_ETABLISSEMENT IN ("30021", "30007", "14768", "19530", "18919") THEN "NATIXIS"
            WHEN ID_ETABLISSEMENT IN ("30056", "11529", "18629", "18799") THEN "HSBC"
            WHEN ID_ETABLISSEMENT IN ("16188", "15930") THEN "BPCE"
            WHEN ID_ETABLISSEMENT = "73829" THEN "ADYEN"
            WHEN ID_ETABLISSEMENT = "12548" THEN "AXA BANQUE"
            WHEN ID_ETABLISSEMENT = "17208" THEN "CHECKOUT"
            WHEN ID_ETABLISSEMENT = "15589" THEN "CREDIT MUTUEL ARKEA"
            WHEN ID_ETABLISSEMENT = "14518" THEN "FORTUNEO"
            WHEN ID_ETABLISSEMENT = "17028" THEN "MONEXT"
            WHEN ID_ETABLISSEMENT IN ("75491", "76630") THEN "STRIPE"
            WHEN ID_ETABLISSEMENT = "10071" THEN "TRESOR PUBLIC"
            WHEN ID_ETABLISSEMENT = "40618" THEN "BOURSORAMA"
            WHEN ID_ETABLISSEMENT = "16908" THEN "MA FRENCH BANK"
            WHEN CD_BANQUE_CB = "30004" THEN "BNP PARIBAS"
            WHEN CD_BANQUE_CB = "30002" THEN "CREDIT LYONNAIS"
            WHEN CD_BANQUE_CB = "30003" THEN "SOCIETE GENERALE"
            WHEN CD_BANQUE_CB = "20041" THEN "BANQUE POSTALE"
            WHEN CD_BANQUE_CB = "30006" THEN "CREDIT AGRICOLE"
            WHEN CD_BANQUE_CB = "30066" THEN "CIC"
            WHEN CD_BANQUE_CB = "19505" THEN CASE
                WHEN ID_ETABLISSEMENT = "19505" THEN "CE AFFILIES"
                WHEN CONTAINS_SUBSTR(LB_ETAB, "CAISSE")
                OR CONTAINS_SUBSTR(LB_ETAB, "CE") THEN "CE"
                ELSE "CE AFFILIES"
            END
            WHEN CD_BANQUE_CB = "30007" THEN CASE
                WHEN ID_ETABLISSEMENT = "94677" THEN "BP AFFILIES"
                WHEN CONTAINS_SUBSTR(LB_ETAB, "B.P.")
                OR CONTAINS_SUBSTR(LB_ETAB, "BANQUE POPULAIRE")
                OR CONTAINS_SUBSTR(LB_ETAB, "BP") THEN "BP"
                WHEN ID_ETABLISSEMENT IN ("10107", "17679") THEN "BP"
                ELSE "BP AFFILIES"
            END
        END AS LB_RESEAU
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_PetitesTables.REF_ETABLISSEMENT`
    WHERE (LB_ETAB IS NOT NULL)
        AND (ID_ETABLISSEMENT IS NOT NULL)
        AND (
            CD_BANQUE_CB IN ("19505", "30007")
            OR ID_ETABLISSEMENT = "30056"
        )
),
COMPENS_REF_ETAB_ACQUEREUR AS (
    SELECT COMPENSATION.*,
        ETAB.LB_RESEAU AS LB_RESEAU_ACQUEREUR,
        (ETAB.LB_RESEAU IS NOT NULL)
        AND (
            ETAB.LB_RESEAU IN (
                "XPOLLENS",
                "PAYPLUG",
                "ONEY",
                "PALATINE",
                "BP AFFILIES",
                "NATIXIS",
                "BPCE",
                "CE AFFILIES",
                "CE",
                "BP"
            )
        ) AS TOP_ON_US
    FROM COMPENSATION
        LEFT JOIN REF_ETAB ETAB USING (CD_BANQUE_ACQUEREUR)
),
COMPENS_REF_ETAB_EMETTEUR AS (
    SELECT COMPENS_REF_ETAB_ACQUEREUR.*,
        ETAB.LB_RESEAU AS LB_RESEAU_EMETTEUR
    FROM COMPENS_REF_ETAB_ACQUEREUR
        LEFT JOIN REF_ETAB ETAB USING (CD_BANQUE_EMETTEUR)
),
REF_DEVISE AS (
    SELECT CD_DEVISE_ISO AS CD_DEVISE,
        LB_DEVISE
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_PetitesTables.REF_DEVISE`
),
COMPENS_REF_DEVISE AS (
    SELECT *
    FROM COMPENS_REF_ETAB_EMETTEUR
        LEFT JOIN REF_DEVISE USING(CD_DEVISE)
),
AUTORISATION AS (
    SELECT NO_CARTE,
        NO_AUTORISATION,
        CD_ERT AS ERT_AUTO,
        IF(
            (
                LEFT(CD_ERT, 1) = "2"
                OR (
                    CD_ERT = "10"
                    AND CD_MODE_LECTURE_CARTE != "1"
                )
                OR CD_ERT = "64"
            ),
            TOP_COMMERCE_ELECTRONIQUE,
            null
        ) AS CD_ECI,
        CASE
            WHEN TOP_COMMERCE_ELECTRONIQUE IS NULL THEN null
            WHEN TOP_COMMERCE_ELECTRONIQUE = "00" THEN "Non applicable"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "01" THEN "MOTO"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "02" THEN "Récurrent"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "03" THEN "Premier paiement"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "04" THEN "Classification non connue"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "05" THEN "Sécurisé"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "06" THEN "Attempt 3DS"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "07" THEN "Non authentifiée"
            WHEN TOP_COMMERCE_ELECTRONIQUE = "08" THEN "Non sécurisé"
            ELSE null
        END AS LB_ECI,
        TOP_EXEMPTION AS CD_INDICATEUR_EXEMPTION,
        CASE
            WHEN LEFT(TOP_EXEMPTION, 4) = "0400" THEN "TRA Acquéreur"
            WHEN LEFT(TOP_EXEMPTION, 4) = "0004" THEN "Hors du scope RTS"
            WHEN LEFT(TOP_EXEMPTION, 4) = "0800" THEN "Low Amount"
            WHEN LEFT(TOP_EXEMPTION, 4) = "8000" THEN "TRA Emetteur"
            WHEN LEFT(TOP_EXEMPTION, 4) = "4000" THEN "Opération récurrente avec montant identique et durée déterminée"
            WHEN LEFT(TOP_EXEMPTION, 4) = "1000" THEN "Implémentation de l'authentification techniquement impossible"
            WHEN LEFT(TOP_EXEMPTION, 4) = "0008" THEN "Péage et parking"
            ELSE null
        END AS LB_INDICATEUR_EXEMPTION,
        IF(
            CD_CRYPTO_COMMERCE_ELECTRONIQUE IS NOT NULL,
            SUBSTR(CD_CRYPTO_COMMERCE_ELECTRONIQUE, 5, 2) = "02"
            OR SUBSTR(CD_CRYPTO_COMMERCE_ELECTRONIQUE, 5, 2) = "01",
            false
        ) AS CRYPTO_ACS,
        IF(
            CD_CRYPTO_COMMERCE_ELECTRONIQUE IS NOT NULL,
            SUBSTR(CD_CRYPTO_COMMERCE_ELECTRONIQUE, 3, 2),
            null
        ) AS CD_METHODE_AUTHENTIFICATION_3DS,
        CD_PAYS_ACQUEREUR AS CD_PAYS_ACQUEREUR_AUTO,
        (CD_MODE_LECTURE_CARTE IS NOT NULL)
        AND (CD_MODE_LECTURE_CARTE = "10")
        AND (
            LEFT(CD_ERT, 1) = "2"
            OR (
                CD_ERT = "10"
                AND CD_MODE_LECTURE_CARTE != "1"
            )
            OR CD_ERT = "64"
        ) AS TOP_COF,
        ID_TRANSACTION_ORIGINE AS REFERENCE_CHAINAGE,
        CD_TYPE_SECURISATION_COMMERCE_ELECTRONIQUE
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_Dataset_Porteur.DS_BHAE_DWH`
    WHERE (
            DT_EXTRACTION BETWEEN DATE("2024-10-01 00:00:00+00:00") AND DATE_ADD(DATE("2025-10-31"), INTERVAL "30" DAY)
        )
        AND (CD_TYPE_MESSAGE = "00110")
        AND (NO_AUTORISATION IS NOT NULL)
),
AUGMENTED_AUTORISATION AS (
    SELECT *,
        (CD_ECI = "06") AS TOP_ATTEMPT_3DS,
        CASE
            WHEN CD_ECI = "06" THEN null
            WHEN CRYPTO_ACS THEN CASE
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "08" THEN "SecurPass avec code"
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "99" THEN "Frictionless"
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "07" THEN "SecurPass biométrique"
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "10" THEN "SMS renforcé"
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "03" THEN "Lecteur CAP"
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "02" THEN "OTP SMS"
                WHEN CD_METHODE_AUTHENTIFICATION_3DS = "09" THEN "SecurPass sous-part"
                ELSE null
            END
            ELSE null
        END AS LB_METHODE_AUTHENTIFICATION_3DS
    FROM AUTORISATION
),
COMPENS_AUTORISATION_ERT AS (
    SELECT *,
        IFNULL(ERT_AUTO, ERT_COMPENS) AS CD_ERT
    FROM COMPENS_REF_DEVISE
        LEFT JOIN AUGMENTED_AUTORISATION USING (NO_CARTE, NO_AUTORISATION)
),
COMPENS_AUTORISATION AS (
    SELECT *,
        CASE
            WHEN CD_PAYS_ACQUEREUR_COMPENS IS NULL THEN IF(
                CD_PAYS_ACQUEREUR_AUTO IS NULL,
                CD_PAYS_COMMERCANT,
                CD_PAYS_ACQUEREUR_AUTO
            )
            ELSE CD_PAYS_ACQUEREUR_COMPENS
        END AS CD_PAYS_ACQUEREUR,
        CASE
            WHEN LEFT(CD_ERT, 1) = "6" THEN "QUASI-CASH"
            WHEN CD_ERT = "70" THEN "RETRAIT"
            WHEN CD_ERT = "75" THEN "CASH ADVANCE"
            WHEN CD_ERT = "30" THEN null
            WHEN CD_ERT = "00" THEN null
            WHEN LEFT(CD_ERT, 1) = "4"
            OR LEFT(CD_ERT, 1) = "5" THEN "AUTOMATE"
            WHEN (
                CD_ERT = "10"
                AND CD_MODE_LECTURE_CARTE != "1"
            ) THEN CASE
                WHEN CD_MODE_LECTURE_CARTE IN ("5", "7")
                AND TOP_XPAY THEN null
                WHEN CD_MODE_LECTURE_CARTE = "3" THEN "PROXIMITE"
                WHEN CD_MODE_LECTURE_CARTE = "5" THEN "PROXIMITE"
                WHEN CD_MODE_LECTURE_CARTE = "7" THEN "PROXIMITE"
                ELSE null
            END
            WHEN (
                LEFT(CD_ERT, 1) = "2"
                OR (
                    CD_ERT = "10"
                    AND CD_MODE_LECTURE_CARTE != "1"
                )
                OR CD_ERT = "64"
            ) THEN CASE
                WHEN TOP_ATTEMPT_3DS THEN "VAD"
                WHEN TOP_COF THEN CASE
                    WHEN CD_ERT IN ("10", "24") THEN IF(
                        CD_TYPE_SECURISATION_COMMERCE_ELECTRONIQUE = "20"
                        OR LB_METHODE_AUTHENTIFICATION_3DS IS NOT NULL,
                        "VADS",
                        "VAD"
                    )
                    ELSE "VAD"
                END
                ELSE IF(
                    CD_TYPE_SECURISATION_COMMERCE_ELECTRONIQUE = "20"
                    OR LB_METHODE_AUTHENTIFICATION_3DS IS NOT NULL,
                    "VADS",
                    "VAD"
                )
            END
            ELSE null
        END AS CD_TYPE_PAIEMENT,
        CASE
            WHEN LEFT(CD_ERT, 1) = "6" THEN "QUASI-CASH"
            WHEN CD_ERT = "70" THEN "RETRAIT"
            WHEN CD_ERT = "75" THEN "CASH ADVANCE"
            WHEN CD_ERT = "30" THEN null
            WHEN CD_ERT = "00" THEN null
            WHEN LEFT(CD_ERT, 1) = "4" THEN "AUTOMATE"
            WHEN LEFT(CD_ERT, 1) = "5" THEN "AUTOMATE NON CB"
            WHEN (
                CD_ERT = "10"
                AND CD_MODE_LECTURE_CARTE != "1"
            ) THEN CASE
                WHEN CD_MODE_LECTURE_CARTE IN ("5", "7")
                AND TOP_XPAY THEN null
                WHEN CD_MODE_LECTURE_CARTE = "3" THEN "PROXIMITE - SANS CONTACT"
                WHEN CD_MODE_LECTURE_CARTE = "5" THEN "PROXIMITE - PUCE"
                WHEN CD_MODE_LECTURE_CARTE = "7" THEN "PROXIMITE - PISTE"
                ELSE null
            END
            WHEN (
                LEFT(CD_ERT, 1) = "2"
                OR (
                    CD_ERT = "10"
                    AND CD_MODE_LECTURE_CARTE != "1"
                )
                OR CD_ERT = "64"
            ) THEN CASE
                WHEN TOP_ATTEMPT_3DS THEN IF(TOP_COF, "VAD - COF", "VAD - VAD")
                WHEN TOP_COF THEN CASE
                    WHEN CD_ERT IN ("10", "24") THEN IF(
                        CD_TYPE_SECURISATION_COMMERCE_ELECTRONIQUE = "20"
                        OR LB_METHODE_AUTHENTIFICATION_3DS IS NOT NULL,
                        "VADS - COF",
                        "VAD - COF"
                    )
                    ELSE "VAD - COF"
                END
                ELSE IF(
                    CD_TYPE_SECURISATION_COMMERCE_ELECTRONIQUE = "20"
                    OR LB_METHODE_AUTHENTIFICATION_3DS IS NOT NULL,
                    "VADS - VADS",
                    "VAD - VAD"
                )
            END
            ELSE null
        END AS LB_TYPE_PAIEMENT
    FROM COMPENS_AUTORISATION_ERT
),
REF_PAYS AS (
    SELECT CD_PAYS_NUMERIQUE,
        LB_PAYS AS LB_PAYS_ACQUEREUR,
        TOP_ZONE_EURO AS CD_ZONE_PAYS,
        CASE
            WHEN TOP_ZONE_EURO = "O" THEN "Union Européenne et Zone euro"
            WHEN TOP_ZONE_EURO = "H" THEN "Union Européenne et Hors zone euro"
            WHEN TOP_ZONE_EURO = "N" THEN "Hors Union Européenne"
            WHEN TOP_ZONE_EURO = "E" THEN "Zone EEE"
            ELSE null
        END AS LB_ZONE_PAYS
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_PetitesTables.REF_PAYS`
),
COMPENS_REF_PAYS AS (
    SELECT *
    FROM COMPENS_AUTORISATION COMPENS
        LEFT JOIN REF_PAYS PAYS ON COMPENS.CD_PAYS_ACQUEREUR = PAYS.CD_PAYS_NUMERIQUE
),
REF_PRODUIT_CARTE AS (
    SELECT CONCAT(CD_RESEAU_SERVICE, CD_PDT_SERVICE) AS CD_PDT_CARTE,
        LB_PDT_SERVICE AS LB_PDT_CARTE
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_PetitesTables.REF_PRODUIT_CARTE`
),
COMPENS_PRODUIT_CARTE AS (
    SELECT *
    FROM COMPENS_REF_PAYS
        LEFT JOIN REF_PRODUIT_CARTE USING(CD_PDT_CARTE)
),
REF_TF AS (
    SELECT DISTINCT NO_CARTE,
        NO_AUTORISATION,
        DATE_DIFF(DT_EXTRACTION, DT_TRANSACTION, DAY) <= 365 AS TOP_TF,
        IF(
            DATE_DIFF(DT_EXTRACTION, DT_TRANSACTION, DAY) <= 365,
            DATE(DT_EXTRACTION),
            null
        ) AS DT_CHARGEMENT_TF
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_Fraude.TF_PORTEUR_DWH`
    WHERE (
            DT_EXTRACTION BETWEEN DATE("2024-10-01 00:00:00+00:00") AND DATE_ADD(DATE("2025-10-31"), INTERVAL "30" DAY)
        )
        AND (NO_AUTORISATION IS NOT NULL)
),
COMPENS_REF_TF AS (
    SELECT *
    FROM COMPENS_PRODUIT_CARTE
        LEFT JOIN REF_TF TF USING(NO_CARTE, NO_AUTORISATION)
),
REF_CODE_ETAB AS(
    SELECT CD_ETAB,
        CD_BQE AS CD_BANQUE_EMETTEUR
    FROM `ib4-pjt-nat-rtl-uat-001-eld4.DP_REF.REF_CORRESPONDANCE_CODE_ETAB`
),
CONTRAT AS(
    SELECT CD_NUM_COMPTE,
        CD_ETAB,
        SAFE_CAST(LI_IDEN AS BIGINT) AS LI_IDEN
    FROM `ib4-pjt-nat-rtl-uat-001-eld4.DP_RACINE_CLIENTS.INPUT_FIC_CONTRAT`
    WHERE TY_ARTICLE != "S"
        AND CD_PRODUIT = "BELI"
),
REF_PORTEUR AS(
    SELECT SAFE_CAST(ID_REFERENCE_DOSSIER_COLLABORATEUR AS BIGINT) AS LI_IDEN,
        CD_ETAB,
        CD_BANQUE_EMETTEUR,
        NO_CARTE
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_Dataset_Porteur.DS_REF_PORTEUR`
        LEFT JOIN REF_CODE_ETAB USING (CD_BANQUE_EMETTEUR)
),
REF_IDBEL_NOCARTE AS(
    SELECT NO_CARTE,
        LI_IDEN,
        CONCAT('["', STRING_AGG(CD_NUM_COMPTE, '", "'), '"]') AS ID_BEL
    FROM REF_PORTEUR
        INNER JOIN CONTRAT USING (LI_IDEN, CD_ETAB)
    GROUP BY NO_CARTE,
        LI_IDEN
),
COMPENS_CD_ETAB AS (
    SELECT *
    FROM COMPENS_REF_TF
        LEFT JOIN REF_CODE_ETAB USING (CD_BANQUE_EMETTEUR)
),
COMPENS_IDBEL AS (
    SELECT *
    FROM COMPENS_CD_ETAB
        LEFT JOIN REF_IDBEL_NOCARTE USING (NO_CARTE)
),
DOSSIERS_SMC AS (
    SELECT NO_DOSSIER_EMETTEUR,
        NO_CARTE,
        DATE(DT_CONTESTATION)
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_Dataset_SMC.DS_SYNTH_DOSSIER_EMETTEUR`
        INNER JOIN (
            SELECT DISTINCT NO_CARTE
            FROM COMPENS_IDBEL
        ) USING(NO_CARTE)
    WHERE (
            DATE(DT_CONTESTATION) BETWEEN DATE("2024-10-01 00:00:00+00:00") AND DATE_ADD(DATE("2025-10-31"), INTERVAL 365 DAY)
        )
),
OPERATIONS_SMC AS (
    SELECT NO_DOSSIER_EMETTEUR,
        NO_CARTE,
        NO_AUTORISATION,
        CD_MCC
    FROM `gni-pjt-nat-rtl-uat-001-bzzc.MONETIQUE_Dataset_SMC.DS_SMC_OPERATIONEMETTEUR`
        INNER JOIN DOSSIERS_SMC USING(NO_DOSSIER_EMETTEUR)
    GROUP BY NO_DOSSIER_EMETTEUR,
        NO_CARTE,
        NO_AUTORISATION,
        CD_MCC
),
COMPENS_SMC AS (
    SELECT COMPENS.*,
        NO_DOSSIER_EMETTEUR AS NO_DOSSIER_SMC
    FROM COMPENS_IDBEL COMPENS
        LEFT JOIN OPERATIONS_SMC USING(NO_CARTE, NO_AUTORISATION)
),
AUGMENTED_COMPENS AS (
    SELECT *,
        (
            (CD_ERT IN ("24", "64", "B1"))
            AND (
                CD_PAYS_ACQUEREUR IN (
                    "276",
                    "040",
                    "056",
                    "100",
                    "196",
                    "191",
                    "208",
                    "724",
                    "233",
                    "246",
                    "250",
                    "300",
                    "348",
                    "372",
                    "352",
                    "428",
                    "380",
                    "438",
                    "440",
                    "442",
                    "470",
                    "578",
                    "528",
                    "616",
                    "620",
                    "203",
                    "642",
                    "703",
                    "705",
                    "752"
                )
            )
            AND NOT(CD_ERT IS null)
            AND NOT(CD_PAYS_ACQUEREUR IS null)
        ) AS TOP_PERIMETRE_RTS,
        CASE
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LECLERC") THEN "LECLERC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CARREFOUR") THEN "CARREFOUR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "INTERMARCHE") THEN "INTERMARCHE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SUPER U")
            OR CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MAGASIN U")
            OR CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "STATION U DAC") THEN "GROUPE U"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AUCHAN") THEN "AUCHAN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PAYPAL")
            OR CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PAYPAL *PAIEMENT 4X") THEN "PAYPAL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "APPLE") THEN "APPLE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "DONALD") THEN "MC DONALD'S"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SNCF") THEN "SNCF"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "VINTED") THEN "VINTED"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AMZN MKTP") THEN "AMAZON MARKETPLACE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GOOGLE") THEN "GOOGLE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "NETFLIX") THEN "NETFLIX"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MARIE BLACHERE") THEN "MARIE BLACHERE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LIDL") THEN "LIDL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AUTOROUTE DU SUD") THEN "AUTOROUTE DU SUD"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RATP") THEN "RATP"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GRAND FRAIS") THEN "GRAND FRAIS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "FDJ") THEN "FDJ"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CDISCOUNT") THEN "CDISCOUNT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ESCOTA") THEN "ESCOTA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BURGER KING") THEN "BURGER KING"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SHEIN") THEN "SHEIN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SPOTIFY") THEN "SPOTIFY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ACTION ") THEN "ACTION"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TEMU") THEN "TEMU"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "FREE") THEN "FREE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "DELIVEROO") THEN "DELIVEROO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BETCLIC") THEN "BETCLIC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LYDIA") THEN "LYDIA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "UBER PAYMENTS") THEN "UBER PAYMENTS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LEBONCOIN") THEN "LEBONCOIN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ALIEXPRESS") THEN "ALIEXPRESS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GIFI") THEN "GIFI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CULTURA") THEN "CULTURA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "NETTO") THEN "NETTO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LEROY MERLIN") THEN "LEROY MERLIN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CASTORAMA") THEN "CASTORAMA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SONY") THEN "SONY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MONOPRIX") THEN "MONOPRIX"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "REVOLUT") THEN "REVOLUT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "INTERSPORT") THEN "INTERSPORT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BRICO DEPOT") THEN "BRICO DEPOT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "IKEA") THEN "IKEA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BRICOMARCHE") THEN "BRICOMARCHE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SELECTA") THEN "SELECTA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "STOKOMANI") THEN "STOKOMANI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KLARNA") THEN "KLARNA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ALDI") THEN "ALDI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "FRANPRIX") THEN "FRANPRIX"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CENTRAKOR") THEN "CENTRAKOR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BOULANGER")
            AND NOT(
                CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BOULANGERIE")
            ) THEN "BOULANGER"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MAXICOFFEE") THEN "MAXICOFFEE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "DISTRI CAFE MERLING") THEN "DISTRI CAFE MERLING"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KIABI") THEN "KIABI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TOOGOODTOG") THEN "TOOGOODTOGO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SANEF") THEN "SANEF AUTOROUTE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "NOZ") THEN "NOZ"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BOLT") THEN "BOLT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CORA") THEN "CORA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CANAL SAT") THEN "CANAL SAT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AIRBNB") THEN "AIRBNB"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BOOKING") THEN "BOOKING"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "FNAC") THEN "FNAC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "3X 4X ONEY") THEN "3X 4X ONEY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WINAMAX") THEN "WINAMAX"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "YVES ROCHER") THEN "YVES ROCHER"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "VEEPEE") THEN "VEEPEE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PICARD SURGELES") THEN "PICARD SURGELES"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SUPERMARCHE MATCH") THEN "SUPERMARCHE MATCH"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "NOCIBE") THEN "NOCIBE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PHOTOMATON") THEN "PHOTOMATON"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TOTAL") THEN "TOTAL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MR BRICOLAGE") THEN "MR BRICOLAGE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TCL") THEN "TCL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "EFFIA") THEN "EFFIA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GAMM VERT") THEN "GAMM VERT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "STARBUCKS") THEN "STARBUCKS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SPAR") THEN "SPAR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ZALANDO") THEN "ZALANDO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BLABLACAR") THEN "BLABLACAR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LA HALLE") THEN "LA HALLE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "VIVAL") THEN "VIVAL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LA MIE CALINE") THEN "LA MIE CALINE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "EasyPark SARL") THEN "EASY PARK"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BIOCOOP") THEN "BIOCOOP"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WEB AMENDE.GOUV") THEN "AMENDE.GOUV"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "STATTELPAYBYPHON") THEN "STATTEL PAY BY PHONE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ZARA") THEN "ZARA "
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WELDOM") THEN "WELDOM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MATCH") THEN "MATCH"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "DECATHLON") THEN "DECATHLON"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PHARMACIE") THEN "PHARMACIE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KFC") THEN "KFC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PLAYSTATION") THEN "PLAYSTATION"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "UBER EATS")
            OR CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "UBER   *EATS") THEN "UBER EATS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "UBER") THEN "UBER"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AMAZON PRIME") THEN "AMAZON PRIME"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AMAZON")
            OR CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AMZ DIGITAL") THEN "AMAZON"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AIR FRANCE") THEN "AIR FRANCE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ALIPAY") THEN "ALIPAY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ALMA") THEN "ALMA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ANNITAK LTD") THEN "ANNITAK LTD"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "AVIS RENT-A-CAR") THEN "AVIS RENT-A-CAR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BACK MARKET") THEN "BACK MARKET"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BIFINITY") THEN "BIFINITY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BINANCE") THEN "BINANCE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BINTENSE") THEN "BINTENSE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BITGET*MULTIEXCHANGE") THEN "BITGET*MULTIEXCHANGE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BITPANDA") THEN "BITPANDA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BRICOMAN") THEN "BRICOMAN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BUNQ B.V") THEN "BUNQ B.V"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BUT VAD") THEN "BUT VAD"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "BVLGARI") THEN "BVLGARI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CARLYLE") THEN "CARLYLE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CASH.REMISEREDUC") THEN "CASH.REMISEREDUC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CATAWIKI") THEN "CATAWIKI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CCBILL.COM *ONLYFANS") THEN "CCBILL.COM *ONLYFANS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CENTER PARCS") THEN "CENTER PARCS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CERTIDEAL") THEN "CERTIDEAL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "CODESDIRECT") THEN "CODESDIRECT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "COMITEO") THEN "COMITEO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "COMPTE NICKEL") THEN "COMPTE NICKEL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "COSMOSPACE") THEN "COSMOSPACE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "DARTY") THEN "DARTY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "DESTINIA") THEN "DESTINIA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "E.LECLERC") THEN "E.LECLERC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "EDREAMS") THEN "EDREAMS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ELECTRO DEPOT FRANCE") THEN "ELECTRO DEPOT FRANCE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ET CAR HIRE") THEN "ET CAR HIRE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ETAM") THEN "ETAM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "FACEBK*") THEN "FACEBK*"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "FARFETCH") THEN "FARFETCH"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GIE PMU SC") THEN "GIE PMU SC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GIFTCARD NOW") THEN "GIFTCARD NOW"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GL HAUSSMANN") THEN "GL HAUSSMANN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "GOVOYAGES") THEN "GOVOYAGES"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "HOTMART B.V.") THEN "HOTMART B.V."
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "IMMOBILIERE 3F") THEN "IMMOBILIERE 3F"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "INSTANT GAMING") THEN "INSTANT GAMING"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KALIMELA LTD") THEN "KALIMELA LTD"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KARD") THEN "KARD"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KIWI.COM") THEN "KIWI.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KLM NETHERLANDS") THEN "KLM NETHERLANDS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "KYCOIN") THEN "KYCOIN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LA POSTE TELECOM") THEN "LA POSTE TELECOM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LENOVO.COM FR") THEN "LENOVO.COM FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "LMNEXT FR SASU") THEN "LMNEXT FR SASU"
            WHEN CONTAINS_SUBSTR(
                UPPER(LB_COMMERCANT),
                "LOUIS VUITTON CHAMPS ELYS"
            ) THEN "LOUIS VUITTON CHAMPS ELYSEES"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MA CARTE CADEAU") THEN "MA CARTE CADEAU"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MA FRENCH BANK") THEN "MA FRENCH BANK"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MAGASIN U") THEN "MAGASIN U"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MAISONSDUMONDE") THEN "MAISONS DU MONDE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MANOMANO") THEN "MANOMANO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MERCURYO") THEN "MERCURYO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MESSIKA GROUP") THEN "MESSIKA GROUP"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MGP*") THEN "MGP*"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MICROSOFT") THEN "MICROSOFT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MISTERFLY SAS") THEN "MISTERFLY SAS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MODMOUNT") THEN "MODMOUNT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MONETAMARKETS.COM") THEN "MONETAMARKETS.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MONEYGRAM FRANCE") THEN "MONEYGRAM FRANCE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "MONISNAP") THEN "MONISNAP"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "NIKE FR") THEN "NIKE FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "OBIZ") THEN "OBIZ"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "OLKYPAY") THEN "OLKYPAY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "OPODO") THEN "OPODO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ORANGE BANK") THEN "ORANGE BANK"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ORANGE MONEY") THEN "ORANGE MONEY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PAYMENTICO.COM") THEN "PAYMENTICO.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PAYPLUG.COM") THEN "PAYPLUG"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PAYSAFECARD") THEN "PAYSAFECARD"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PIERRE&VACANCES") THEN "PIERRE&VACANCES"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PLEBICOM") THEN "PLEBICOM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PRINTEMPS") THEN "PRINTEMPS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PROBILLER.COM") THEN "PROBILLER.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PROMOVACANCES") THEN "PROMOVACANCES"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PSGBILLETTERIEFOOT") THEN "PSGBILLETTERIEFOOT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PSOCIETES.COM") THEN "PSOCIETES.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PUPRIME.COM") THEN "PUPRIME.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "PYD*") THEN "PYD*"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RAKUTEN") THEN "RAKUTEN"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RAPIDO") THEN "RAPIDO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RECHARGE BLING") THEN "RECHARGE BLING"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "REDUCPRIV.COM") THEN "REDUCPRIV.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "REMISEREDUC.FR") THEN "REMISEREDUC.FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "REMITLY") THEN "REMITLY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RENTALCARS.COM") THEN "RENTALCARS.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RIOT*") THEN "RIOT*"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "RUMBO") THEN "RUMBO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SAMSUNG FRANCE") THEN "SAMSUNG FRANCE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SCALAPAY*") THEN "SCALAPAY*"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SENDWAVE") THEN "SENDWAVE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SFR ONE SHOT SVI") THEN "SFR ONE SHOT SVI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SHOPPING MDS") THEN "SHOPPING MDS"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SIXT CAR RENTAL") THEN "SIXT CAR RENTAL"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SOGEXIA S.A.SOGEXIA S.A.") THEN "SOGEXIA S.A.SOGEXIA S.A."
            WHEN CONTAINS_SUBSTR(
                UPPER(LB_COMMERCANT),
                "STAYFORLONG.COM ONLINE HO"
            ) THEN "STAYFORLONG.COM ONLINE HO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "SUPER U") THEN "SUPER U"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TAPTAP SEND BE") THEN "TAPTAP SEND BE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TIKTOK") THEN "TIKTOK"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TRA*BUDGETAIR.FR.") THEN "TRA*BUDGETAIR.FR."
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TRADE REPUBLIC") THEN "TRADE REPUBLIC"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TRANSAVIA") THEN "TRANSAVIA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TRANSFERGO") THEN "TRANSFERGO"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TRANSFERWISE") THEN "TRANSFERWISE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TRIP.COM") THEN "TRIP.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "TWITCH") THEN "TWITCH"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "UBALDI") THEN "UBALDI"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "UNIBET FR") THEN "UNIBET FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "VANTAGE") THEN "VANTAGE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WECHATPAY") THEN "WECHATPAY"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WESTERN UNION") THEN "WESTERN UNION"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WISE") THEN "WISE"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WORLDREMIT") THEN "WORLDREMIT"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WR-INFO.COM") THEN "WR-INFO.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WWW ZALANDO FR") THEN "WWW ZALANDO FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WWW.EMRYSLACARTE.FR") THEN "WWW.EMRYSLACARTE.FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "WWW.GROUPON.FR") THEN "WWW.GROUPON.FR"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "XSOLLA") THEN "XSOLLA"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "YSL.COM") THEN "YSL.COM"
            WHEN CONTAINS_SUBSTR(UPPER(LB_COMMERCANT), "ZEN.COM UAB") THEN "ZEN.COM UAB"
            ELSE null
        END AS LB_NOM_COMMERCANT
    FROM COMPENS_SMC
)
SELECT NO_CARTE,
    BIN6,
    NO_AUTORISATION,
    CD_BANQUE_ACQUEREUR,
    LB_BANQUE_ACQUEREUR,
    LB_RESEAU_ACQUEREUR,
    TOP_ON_US,
    CD_BANQUE_EMETTEUR,
    LB_BANQUE_EMETTEUR,
    LB_RESEAU_EMETTEUR,
    LB_COMMERCANT,
    IF(
        LB_NOM_COMMERCANT IS NULL,
        "Autre",
        LB_NOM_COMMERCANT
    ) AS LB_NOM_COMMERCANT,
    CD_PAYS_COMMERCANT,
    CD_DEVISE,
    LB_DEVISE,
    CD_ECI,
    IF(CD_ECI IS NULL, null, LB_ECI) AS LB_ECI,
    IF(
        TOP_ATTEMPT_3DS IS NULL
        OR LB_TYPE_PAIEMENT IS NULL,
        false,
        IF(CD_TYPE_PAIEMENT = "VAD", TOP_ATTEMPT_3DS, false)
    ) AS TOP_ATTEMPT_3DS,
    CD_ERT,
    IF(
        CD_TYPE_PAIEMENT IN ("VAD", "VADS"),
        CD_INDICATEUR_EXEMPTION,
        null
    ) AS CD_INDICATEUR_EXEMPTION,
    IF(
        CD_TYPE_PAIEMENT IN ("VAD", "VADS"),
        LB_INDICATEUR_EXEMPTION,
        null
    ) AS LB_INDICATEUR_EXEMPTION,
    CD_MCC,
    LB_MCC,
    IF(
        CD_TYPE_PAIEMENT IN ("AUTOMATE", "PROXIMITE", "RETRAIT", "QUASI-CASH"),
        null,
        CD_METHODE_AUTHENTIFICATION_3DS
    ) AS CD_METHODE_AUTHENTIFICATION_3DS,
    IF(
        CD_TYPE_PAIEMENT IN ("AUTOMATE", "PROXIMITE", "RETRAIT", "QUASI-CASH"),
        null,
        LB_METHODE_AUTHENTIFICATION_3DS
    ) AS LB_METHODE_AUTHENTIFICATION_3DS,
    CD_MODE_LECTURE_CARTE,
    LB_MODE_LECTURE_CARTE,
    CD_NATURE_OPERATION,
    LB_NATURE_OPERATION_MONETIQUE,
    CD_ORIGINE_FLUX,
    LB_ORIGINE_FLUX,
    CD_PAYS_ACQUEREUR,
    LB_PAYS_ACQUEREUR,
    CD_PDT_CARTE,
    LB_PDT_CARTE,
    TOP_VISA_NATIVE,
    CD_SCHEME,
    LB_SCHEME,
    ID_TOKEN_REQUESTOR,
    LB_TOKEN_REQUESTOR,
    IF(
        TOP_XPAY IS NULL
        OR LB_TYPE_PAIEMENT IS NULL,
        false,
        TOP_XPAY
    ) AS TOP_XPAY,
    CD_TYPE_DEBIT,
    CD_TYPE_PAIEMENT,
    LB_TYPE_PAIEMENT,
    IF(
        TOP_COF IS NULL
        OR LB_TYPE_PAIEMENT IS NULL
        OR CD_TYPE_PAIEMENT IN ("AUTOMATE", "PROXIMITE", "RETRAIT", "QUASI-CASH"),
        false,
        TOP_COF
    ) AS TOP_COF,
    CD_ZONE_PAYS,
    LB_ZONE_PAYS,
    DT_COMPENSATION,
    DT_TRANSACTION,
    MONTANT,
    MT_TRANCHE_RTS,
    NO_CONTRAT_COMMERCANT,
    NO_SIRET,
    REFERENCE_CHAINAGE,
    TOP_FACTURE_CREDIT,
    TOP_PERIMETRE_RTS,
    IF(TOP_TF IS NULL, false, TOP_TF) AS TOP_TF,
    DT_CHARGEMENT_TF,
    NO_DOSSIER_SMC,
    ID_BEL,
    CD_ETAB
FROM AUGMENTED_COMPENS
;