name: Gradle Verify

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      max-parallel: 1
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: LANG=en_US.UTF-8 ./gradlew check jacocoTestReport jacocoTestCoverageVerification coveralls
